In [45]:
using Flux

W = param(rand(10,10,10))
x = ones(10,10,10)
x = W .* x
size(x)

(10, 10, 10)

In [43]:
sum(W[1])

UndefVarError: UndefVarError: onehot not defined

In [13]:
using Flux: onehot, onecold, onehotbatch
onehot(8, 1:10)

10-element Flux.OneHotVector:
 false
 false
 false
 false
 false
 false
 false
  true
 false
 false

In [51]:
label = zeros(10)
label[3] = 1
label

10-element Array{Float64,1}:
 0.0
 0.0
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [59]:
using Flux: crossentropy
using LinearAlgebra
m = Chain(
  Dense(28^2, 128, relu),
  Dense(128, 32, relu),
  Dense(32, 10), softmax)

loss(x, y) = crossentropy(m(x), y) + sum(norm, params(m))

loss(rand(28^2), rand(10))

38.15597181748389 (tracked)

In [2]:
using Base.Iterators: repeated, partition
# mb_idxs = partition(1:length(train_imgs), batch_size)
#
# partition takes one array of eg. indexes and a batch size and splits the array according to the batch size into subarrays
# the last partition may be smaller  
idxs = partition(1:1000, 128)
for i in idxs
    @show(length(i))
    @show(i)
end

length(i) = 128
i = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128]
length(i) = 128
i = [129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 2

In [33]:
Y = [1, 2, 3, 4, 5, 6, 7, 8, 7, 3, 3, 4, 5, 3, 4, 2, 4, 5]
@show(Y')

idxs = partition(1:length(Y), 3)
for i in idxs 
    #@show(i)
    @show(onehotbatch(Y[i], 0:9))
end


# onehotbatch returns a bool matrix structured the following:
# 10 x batchsize

Y


Y' = [1 2 3 4 5 6 7 8 7 3 3 4 5 3 4 2 4 5]
onehotbatch(Y[i], 0:9) = Bool[false false false; true false false; false true false; false false true; false false false; false false false; false false false; false false false; false false false; false false false]
onehotbatch(Y[i], 0:9) = Bool[false false false; false false false; false false false; false false false; true false false; false true false; false false true; false false false; false false false; false false false]
onehotbatch(Y[i], 0:9) = Bool[false false false; false false false; false false false; false false false; false false false; false false false; false false false; true false true; false true false; false false false]
onehotbatch(Y[i], 0:9) = Bool[false false false; false false false; false false false; true true false; false false true; false false false; false false false; false false false; false false false; false false false]
onehotbatch(Y[i], 0:9) = Bool[false false false; false false false; false false false; fa

18-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8
 7
 3
 3
 4
 5
 3
 4
 2
 4
 5

In [28]:
A = rand(32, 32, 1, 30)
size(A, 1)
A[:, :, :, 30]

32×32×1 Array{Float64,3}:
[:, :, 1] =
 0.51359    0.613994    0.0654633   …  0.851326   0.509411   0.99978    
 0.548908   0.65033     0.121337       0.510888   0.774793   0.264831   
 0.400322   0.647701    0.00971605     0.185003   0.531566   0.140485   
 0.963693   0.827483    0.655745       0.771081   0.794697   0.851116   
 0.714847   0.579359    0.200482       0.740648   0.198052   0.708952   
 0.79805    0.821157    0.0915145   …  0.77625    0.421517   0.804504   
 0.670384   0.153121    0.798156       0.832818   0.676467   0.106371   
 0.377475   0.577047    0.859263       0.248664   0.326639   0.525787   
 0.596635   0.418763    0.622254       0.988054   0.281203   0.829801   
 0.324293   0.501648    0.756843       0.255408   0.333663   0.449823   
 0.172998   0.769347    0.57481     …  0.613288   0.854644   0.957427   
 0.17118    0.09037     0.237762       0.882528   0.955967   0.689875   
 0.717176   0.19012     0.579087       0.0406183  0.457039   0.875447   
 ⋮           

In [38]:
A = [(1, 2), (2, 2), (3, 3), (5, 6)]
A[4][2]

6

In [21]:
using Statistics

A = rand(10, 10, 1, 10)
A[1, 1, 1, 1] = 0
#display(A)
A_tmp = A
A_tmp[A_tmp.==0] .= 1
display(A)
mean_img = mean(A, dims=4)
std(A, mean=mean_img, dims=4)
size(A, 4)
@info(typeof(A))
B = convert(Array{Float32}, A)
@info(typeof(B))


10×10×1×10 Array{Float64,4}:
[:, :, 1, 1] =
 1.0        0.0559654  0.927587    …  0.474131  0.421222   0.819239
 0.692788   0.751365   0.927513       0.792072  0.0628086  0.347872
 0.849696   0.443913   0.631879       0.41924   0.309137   0.503724
 0.191983   0.940135   0.371415       0.662442  0.273187   0.664371
 0.45978    0.115646   0.00548218     0.587543  0.817029   0.497479
 0.801733   0.136959   0.755487    …  0.99323   0.113091   0.205687
 0.0640208  0.622022   0.76989        0.889754  0.102038   0.354527
 0.272907   0.849542   0.866156       0.318319  0.827114   0.284741
 0.292484   0.594488   0.457933       0.742388  0.934849   0.658638
 0.576974   0.893353   0.178604       0.722438  0.419641   0.465409

[:, :, 1, 2] =
 0.24695    0.113818   0.458468  0.336884  …  0.445521  0.578942  0.815727 
 0.0839413  0.305156   0.871841  0.417761     0.533901  0.673977  0.0517769
 0.477927   0.0858619  0.381923  0.577226     0.237609  0.66303   0.383123 
 0.348278   0.609628   0.156143 

┌ Info: Array{Float64,4}
└ @ Main In[21]:12
┌ Info: Array{Float32,4}
└ @ Main In[21]:14


In [1]:
using ProgressMeter 
@showprogress 1 "Computing..." for i in 1:50
    sleep(0.1)
end


Computing...100%|███████████████████████████████████████| Time: 0:00:05


In [59]:
#using LinearAlgebra
using Flux
m = Dense(2, 2)
display(params(m))
#B = sum(norm, params(m))
B = norm(params(m))
display(typeof(B))
B = Flux.Tracker.TrackedReal{Float32}(B)
typeof(B)

Params([Float32[-0.554384 -0.930772; -0.312058 -0.0832845] (tracked), Float32[0.0, 0.0] (tracked)])

Tracker.TrackedReal{Float64}

ErrorException: Not implemented: convert tracked Float64 to tracked Float32